controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# WebProfiler routes (development only)
when@dev:
    _profiler:
        resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
        prefix: /_profiler

    _wdt:
        resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
        prefix: /_wdt
