services:
  dropcrypt:
    build: .
    container_name: dropcrypt
    ports:
      - "8080:5000"
    volumes:
      - ./data:/app/data
      - ./static:/app/static
      - ./templates:/app/templates
      - ./translations/de/LC_MESSAGES/messages.po:/app/translations/de/LC_MESSAGES/messages.po
      - ./translations/en/LC_MESSAGES/messages.po:/app/translations/en/LC_MESSAGES/messages.po
      - ./app.py:/app/app.py
      - ./encryption.py:/app/encryption.py
      - ./database.py:/app/database.py
      - ./.env:/app/.env
    restart: unless-stopped
    environment:
      - FLASK_DEBUG=1  # Aktiviert Flask Debug-Modus
      - PYTHONUNBUFFERED=1  # Python Output wird nicht gepuffert
      - POSTGRES_HOST=db  # Override .env for Docker networking
    networks:
      - dropcrypt-network
    depends_on:
      - db

  cleanup:
    build:
      context: .
      dockerfile: Dockerfile.cleanup
    container_name: dropcrypt-cleanup
    restart: unless-stopped
    volumes:
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_HOST=db  # Override .env for Docker networking
    networks:
      - dropcrypt-network
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: dropcrypt-db
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dropcrypt-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: dropcrypt-adminer
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
    networks:
      - dropcrypt-network
    depends_on:
      - db
    restart: unless-stopped

networks:
  dropcrypt-network:
    driver: bridge

volumes:
  postgres_data:
