services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/public:/var/www/public
    depends_on:
      - php
    networks:
      - dropcrypt-network

  php:
    build:
      context: ./backend
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./backend:/var/www
    networks:
      - dropcrypt-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-dropcrypt}
      POSTGRES_USER: ${DB_USER:-dropcrypt}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-dropcrypt}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dropcrypt-network

networks:
  dropcrypt-network:
    driver: bridge

volumes:
  postgres_data: 