services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - dropcrypt

  php:
    build:
      context: ./backend
      dockerfile: docker/Dockerfile
    volumes:
      - ./backend:/var/www
    environment:
      - APP_ENV=dev
      - DATABASE_URL=postgresql://dropcrypt:dropcrypt@postgres:5432/dropcrypt?serverVersion=15&charset=utf8
    depends_on:
      - postgres
    networks:
      - dropcrypt

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=dropcrypt
      - POSTGRES_PASSWORD=dropcrypt
      - POSTGRES_DB=dropcrypt
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dropcrypt

networks:
  dropcrypt:
    driver: bridge

volumes:
  postgres_data: 